### ISSUE TITLE
README.mdに.NET 6の確認方法を。

### ISSUE THREAD

**Issue by smk7758** [karoterra/AupRename#3]
.NET 6を確認する方法を書いてほしい。
---
下記コマンドを実行し、`Microsoft.WindowsDesktop.App 6.0.10`がリストアップされていたらインストール済みである。
```
dotnet --list-runtimes
```

**Comment by karoterra** [comment]
READMEに.NET 6ランタイムがインストールされているか確認する方法と、ランタイムの入手先について追記しました。
